import { Herbal } from "./herbal";

export interface Author {
    id: string;
    name: string;
    slug: string;
    alias?: string;
    biography?: string;
    career?: string;
    achievements?: string;
    contributions?: string;
    works?: string;
    philosophy?: string;
    legacy?: string;
    birthDate?: string;
    deathDate?: string;
    birthPlace?: string;
    deathPlace?: string;
    era?: string;
    dynasty?: string;
    specialty?: string;
    teacher?: string;
    students?: string;
    portrait?: string;
    avatar?: string;
    coverImage?: string;
    galleryImages?: string[];
    quotes?: string;
    anecdotes?: string;
    honors?: string;
    memorials?: string;
    references?: string;
    viewCount: number;
    likeCount: number;
    isActive: boolean;
    herbals?: Herbal[];
    folkMedicines?: Herbal[];
    createdAt: Date;
    updatedAt: Date;
  }